# Generated by Django 4.2.7 on 2024-03-19 16:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import material.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('year_of_publication', models.CharField(blank=True, max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('ebooks_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Practice_Problems', 'Practice Problems')], max_length=50, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Valid Ebook formats: jpg, png', null=True, upload_to=material.models.Ebook.e_books_cover, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('files', models.FileField(help_text='Valid Ebook formats: pdf, docx', null=True, upload_to=material.models.Ebook.e_books_folder, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])])),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.category')),
            ],
        ),
    ]
