# Generated by Django 4.2.7 on 2024-04-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
