# Generated by Django 4.2.7 on 2024-03-27 15:08

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=base.models.Message.image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf', 'docx', 'doc'])]),
        ),
    ]
